version: '3.9'

services: 
  api:
    build: ./api
    hostname: api 
    volumes:
      - ./api/code:/app
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}      
  consumer:
    build: ./consumer/
    hostname: consumer 
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_ENDPOINT=${API_ENDPOINT}
    volumes:
      - ./consumer/code:/app
    ports:
      - "80:80"
  dba:
    container_name: dba
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGA_ADMIN_NAME}
      - PGADMIN_DEFAULT_PASSWORD=${PGA_ADMIN_PASS}
    ports:
      - "5050:80"
  db:
    container_name: db
    image: postgres:12.12
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/docker-entrypoint-initdb.d
